route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'rocketchat'
receivers:
- name: 'rocketchat'
  webhook_configs:
  - send_resolved: true
    url: 'http://xxxx'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
